version: 2.1
orbs:
  node: circleci/node@3.0
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: node:17.8.0
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run: npm run test

      - codecov/upload:
          file: {{ coverage_report_filepath }}
          token: 2f9ddeb1-ebe3-4f90-b5a6-236bd0ec2ef3